### ISSUE TITLE
UI / UX 

### ISSUE THREAD

**Issue by augmen** [ooade/PreactSimpleStarter#52]
how to build UI / UX for the pwa app. Any docs ?

**Comment by ooade** [comment]
This repo won't have docs for that because it's Preact Simple Starter; Boilerplate for creating PWA's
If you're into creating UI / UX for your Preact App, you could check out some useful components [here](https://github.com/ooade/awesome-preact#components)

Besides, UI / UX is done like any other SPA's. Being a PWA is just by adding a manifest file, a service worker file and making sure we're not blocking the main thread(async or defer js files). And, there're some pretty better stuff you could do, like lazy loading images (which we don't currently have), because it's of course a "Simple Starter" and some pretty other better stuff :sweat_smile:
